name: Tag and release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Manually set release version
        required: false
        type: string

jobs:
  tag_release:
    runs-on: ubuntu-latest
    steps:
      - name: Create tag
        uses: mathieudutour/github-tag-action@v6.1
        id: tag_version
        with:
          custom_tag: ${{ inputs.version }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        uses: ncipollo/release-action@v1.14.0
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: ${{ steps.tag_version.outputs.new_version }}
          body: ${{ steps.tag_version.outputs.changelog }}
